version: '3.8'
services:
  app:
    image: backend_qlope
    container_name: backend_qlope
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: qlope_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel: